export const ALL_MESSAGE_OPTION = "ALL_MESSAGE_OPTION";
export const CONTACT_LIST_OPTION = "CONTACT_LIST_OPTION";
export const NOTIFICATION_OPTION = "NOTIFICATION_OPTION";
export const PROFILE_OPTION = "PROFILE_OPTION";
export const ADD_FRIEND_OPTION = "ADD_FRIEND_OPTION";
export const FRIENDS_OPTION = "FRIENDS_OPTION";
export const CANCEL_REQUEST_OPTION = "CANCEL_REQUEST_OPTION";
export const ACCEPT_REQUEST_OPTION = "ACCEPT_REQUEST_OPTION";