export const ALL_MESSAGES_OPTION = "ALL_MESSAGES_OPTION";
export const FRIENDs_OPTION = "FRIENDs_OPTION";
export const FRIEND_REQUESTS_OPTION = "FRIEND_REQUESTS_OPTION";
export const PROFILE_OPTION = "PROFILE_OPTION";
export const ADD_FRIEND_OPTION = "ADD_FRIEND_OPTION";
export const FRIENDS_OPTION = "FRIENDS_OPTION";
export const CANCEL_REQUEST_OPTION = "CANCEL_REQUEST_OPTION";
export const ACCEPT_REQUEST_OPTION = "ACCEPT_REQUEST_OPTION";