export const ALL_MESSAGE_OPTION = "ALL_MESSAGE_OPTION";
export const CONTACT_LIST_OPTION = "CONTACT_LIST_OPTION";
export const NOTIFICATION_OPTION = "NOTIFICATION_OPTION";
export const PROFILE_OPTION = "PROFILE_OPTION";